<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="AppState.fs" />
    <Compile Include="EvolutionLayout.fs" />
    <Compile Include="Views.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.FuncUI" />
    <PackageReference Include="Avalonia.FuncUI.Elmish" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../FsHarness.Core/FsHarness.Core.fsproj" />
    <ProjectReference Include="../FsHarness.Codex/FsHarness.Codex.fsproj" />
    <ProjectReference Include="../FsHarness.Infrastructure/FsHarness.Infrastructure.fsproj" />
  </ItemGroup>
</Project>
